### ISSUE TITLE
Autogen: No checking for consistency of job_record, input job_record, and actual input files.

### ISSUE THREAD

**Issue by bbusemeyer** [QWalk/mainline#4]
I'm planning on implementing this, and possibly a check that all the keys of the job_record are used, since it's easy to accidentally misname a key, and have it not be used (for example, setting job_record['id'] instead of job_record['control']['id'])

**Comment by bbusemeyer** [comment]
With my current pull request, Autogen now checks consistency of DFT input and job_record. Everything except job_record['control'] should match between the JSON in the directory and the input job_record already as it is now.

**Comment by lkwagner** [comment]
We don't quite want this behavior, though. For example, consider two cases:
1) We want to tighten the error bars on DMC. In that case, we rerun the same job_records with the dmc tolerance increased. The job_record will not match the one in the directory.
2) We want to loosen the convergence of LINEAR. For example, suppose that for some reason we set the tolerance for LINEAR too low and it's never converging. It's totally fine to loosen that convergence and move on, but the job_record wouldn't match.

On Monday, we discussed what I think would be a better solution for these problems:
1) A data structure that follows the job_record data structure, but elements are dictionaries containing:
'default' : default value
'documentation':string containing documentation of the option
This is then the documentation for the allowed elements and also the defaults in one place.
2) A function which takes the documentation data structure and a proposed job_record. If there are keys in the proposed job_record which are not in the documentation data structure, then raise an error.
3) the default function can now just run through the data structure and generate a default record, instead of having the defaults hard-coded.

**Comment by bbusemeyer** [comment]
I agree, sorry, what I meant by "everything except job_record['control'] should match between the JSON in the directory and the input job_record already as it is now," was that if a user updated the options you mentioned (DMC error bar, or convergence criteria of LINEAR), initially, the job_records would be different, but at the end of `execute()`, it performs `json.dump(record,f)`, which will replace the JSON with the new job_record. Because of this everything except the 'control' section will (correctly) match after the `execute()` is done. With the DFT input checker, it'll also ensure that DFT inputs match job_record, and with the data structure you mentioned above, all the goals I commented on should be accomplished.
